In [1]:
import sys 
sys.path.append('/home/hydrogen/workspace/Space_GW/pespace')
sys.path.append('/home/hydrogen/workspace/Space_GW/wf4ti')

import numpy as np
import h5py
from matplotlib import pyplot as plt
%matplotlib inline


In [2]:
# file_path = "/home/hydrogen/workspace/Space_GW/LDC/LDC_data/LDC1-1_MBHB_v2_TD_9gc2s16.hdf5"
file_path = "/home/hydrogen/workspace/Space_GW/LDC/LDC_data/LDC1-1_MBHB_v1_1_TD.hdf5"
with h5py.File(file_path, "r") as f:
    # f.visit(lambda name: print(name))

    source_parameters = {}
    print('Source information: ')
    for parameter, value in f["H5LISA/GWSources/MBHB-0"].items():
        # print(f"{parameter}: {value[()]}")
        source_parameters[parameter] = value[()]

    # print(f["H5LISA/PreProcess/TDIGenerator"][()])
    TDI_data = f["H5LISA/PreProcess/TDIdata"][()]
    print(TDI_data)
    print(TDI_data.shape)


Source information: 
[[ 1.00000000e+01  1.43833880e-20  2.60735822e-20 -3.76029487e-20]
 [ 2.00000000e+01 -4.00786160e-20 -1.10577887e-20  8.30232332e-20]
 [ 3.00000000e+01  5.03369389e-20 -4.04076805e-21 -8.91464442e-20]
 ...
 [ 4.19430200e+07 -9.93639790e-21  5.14937840e-21 -3.06222993e-21]
 [ 4.19430300e+07 -4.46619576e-21  9.52535015e-21  3.00762453e-20]
 [ 4.19430400e+07 -1.15332474e-21 -2.70341628e-20 -3.94004181e-22]]
(4194304, 4)


In [10]:
time_samples = TDI_data[:,0]
TDI_strain = TDI_data[:,1:]
print(TDI_strain)
print(TDI_strain.shape)
TDI_strain = TDI_strain.T
print(TDI_strain)
print(TDI_strain.shape)

duration = time_samples[-1]-time_samples[0]
cadence = time_samples[1]-time_samples[0]
print('duration: ', duration)
print('cadence: ', cadence)



[[ 1.43833880e-20  2.60735822e-20 -3.76029487e-20]
 [-4.00786160e-20 -1.10577887e-20  8.30232332e-20]
 [ 5.03369389e-20 -4.04076805e-21 -8.91464442e-20]
 ...
 [-9.93639790e-21  5.14937840e-21 -3.06222993e-21]
 [-4.46619576e-21  9.52535015e-21  3.00762453e-20]
 [-1.15332474e-21 -2.70341628e-20 -3.94004181e-22]]
(4194304, 3)
[[ 1.43833880e-20 -4.00786160e-20  5.03369389e-20 ... -9.93639790e-21
  -4.46619576e-21 -1.15332474e-21]
 [ 2.60735822e-20 -1.10577887e-20 -4.04076805e-21 ...  5.14937840e-21
   9.52535015e-21 -2.70341628e-20]
 [-3.76029487e-20  8.30232332e-20 -8.91464442e-20 ... -3.06222993e-21
   3.00762453e-20 -3.94004181e-22]]
(3, 4194304)
duration:  41943030.0
cadance:  10.0
